steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "--build-arg",
        "NEXT_PUBLIC_APP_API_URL=https://nest-generic-backend-xlqdbkwfma-ue.a.run.app",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "next-generic-backoffice",
        "--image",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "--region",
        "us-east1",
        "--platform",
        "managed",
        "--port",
        "8080",
        "--allow-unauthenticated",
      ]
timeout: 900s
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
